export const BASE_URL = 'http://api.openweathermap.org';

export const LIST_RESPONSE_REQUEST = 'LIST_RESPONSE_REQUEST';

export const LIST_RESPONSE_SUCCESS = 'LIST_RESPONSE_SUCCESS';

export const LIST_RESPONSE_FAIL = 'LIST_RESPONSE_FAIL';

export const CITY_RESPONSE_REQUEST = 'CITY_RESPONSE_REQUEST';

export const CITY_RESPONSE_SUCCESS = 'CITY_RESPONSE_SUCCESS';

export const CITY_RESPONSE_FAIL = 'CITY_RESPONSE_FAIL';
